interface IList {
   "item_category_name": string,
   "item_code": number,
   "item_name": string,
   "kind_code": number,
   "kind_name": string,
   "wholesale_shipping_unit": string | null,
   "wholesale_shipping_scale": number | null,
   "retail_shipping_unit": string | null,
   "retail_shipping_scale": number | null,
   "organic_shipping_unit": string | null,
   "organic_shipping_scale": number | null,
   "wholesale_grade": string | null,
   "retail_grade": string | null,
   "organic_grade": string | null
}

interface IProductList {
   category_Code : string,
   name : string,
   list : IList[],
}

const FOOD_CROPS  = [
    {
       "item_category_name": "식량작물",
       "item_code": 111,
       "item_name": "쌀",
       "kind_code": 1,
       "kind_name": "일반계",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 20,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 111,
       "item_name": "쌀",
       "kind_code": 2,
       "kind_name": "백미",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 4,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 111,
       "item_name": "쌀",
       "kind_code": 3,
       "kind_name": "현미",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 2,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 111,
       "item_name": "쌀",
       "kind_code": 5,
       "kind_name": "햇일반계",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 20,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 112,
       "item_name": "찹쌀",
       "kind_code": 1,
       "kind_name": "일반계",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 40,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 113,
       "item_name": "혼합곡",
       "kind_code": 0,
       "kind_name": "혼합곡",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 800,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 141,
       "item_name": "콩",
       "kind_code": 1,
       "kind_name": "흰 콩(국산)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 35,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 141,
       "item_name": "콩",
       "kind_code": 2,
       "kind_name": "콩나물콩",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 35,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 141,
       "item_name": "콩",
       "kind_code": 3,
       "kind_name": "흰 콩(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 35,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 142,
       "item_name": "팥",
       "kind_code": 0,
       "kind_name": "붉은 팥(국산)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 40,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 142,
       "item_name": "팥",
       "kind_code": 1,
       "kind_name": "붉은 팥(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 40,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 143,
       "item_name": "녹두",
       "kind_code": 0,
       "kind_name": "국산",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 40,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 143,
       "item_name": "녹두",
       "kind_code": 1,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 40,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 144,
       "item_name": "메밀",
       "kind_code": 1,
       "kind_name": "메밀(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 151,
       "item_name": "고구마",
       "kind_code": 0,
       "kind_name": "밤",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 800,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 152,
       "item_name": "감자",
       "kind_code": 1,
       "kind_name": "수미",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 152,
       "item_name": "감자",
       "kind_code": 2,
       "kind_name": "대지마",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "식량작물",
       "item_code": 161,
       "item_name": "귀리",
       "kind_code": 1,
       "kind_name": "귀리",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 162,
       "item_name": "보리",
       "kind_code": 1,
       "kind_name": "보리",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 800,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 163,
       "item_name": "수수",
       "kind_code": 1,
       "kind_name": "수수",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 400,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "식량작물",
       "item_code": 164,
       "item_name": "율무",
       "kind_code": 1,
       "kind_name": "율무",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 400,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    }
 ]

const VEGETABLES = [
    {
       "item_category_name": "채소류",
       "item_code": 211,
       "item_name": "배추",
       "kind_code": 1,
       "kind_name": "봄",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "포기",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 211,
       "item_name": "배추",
       "kind_code": 2,
       "kind_name": "고랭지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "포기",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 211,
       "item_name": "배추",
       "kind_code": 3,
       "kind_name": "가을",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "포기",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 211,
       "item_name": "배추",
       "kind_code": 6,
       "kind_name": "월동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "포기",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 212,
       "item_name": "양배추",
       "kind_code": 0,
       "kind_name": "양배추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "포기",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 213,
       "item_name": "시금치",
       "kind_code": 0,
       "kind_name": "시금치",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 200,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 214,
       "item_name": "상추",
       "kind_code": 1,
       "kind_name": "적",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 214,
       "item_name": "상추",
       "kind_code": 2,
       "kind_name": "청",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 215,
       "item_name": "얼갈이배추",
       "kind_code": 0,
       "kind_name": "얼갈이배추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 216,
       "item_name": "갓",
       "kind_code": 0,
       "kind_name": "갓",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 221,
       "item_name": "수박",
       "kind_code": 0,
       "kind_name": "수박",
       "wholesale_shipping_unit": "개",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 222,
       "item_name": "참외",
       "kind_code": 0,
       "kind_name": "참외",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 223,
       "item_name": "오이",
       "kind_code": 1,
       "kind_name": "가시계통",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 223,
       "item_name": "오이",
       "kind_code": 2,
       "kind_name": "다다기계통",
       "wholesale_shipping_unit": "개",
       "wholesale_shipping_scale": 100,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 223,
       "item_name": "오이",
       "kind_code": 3,
       "kind_name": "취청",
       "wholesale_shipping_unit": "개",
       "wholesale_shipping_scale": 50,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 224,
       "item_name": "호박",
       "kind_code": 1,
       "kind_name": "애호박",
       "wholesale_shipping_unit": "개",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 200,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 224,
       "item_name": "호박",
       "kind_code": 2,
       "kind_name": "쥬키니",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 224,
       "item_name": "호박",
       "kind_code": 3,
       "kind_name": "단호박",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 225,
       "item_name": "토마토",
       "kind_code": 0,
       "kind_name": "토마토",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 226,
       "item_name": "딸기",
       "kind_code": 0,
       "kind_name": "딸기",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 500,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 231,
       "item_name": "무",
       "kind_code": 1,
       "kind_name": "봄",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 800,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 231,
       "item_name": "무",
       "kind_code": 2,
       "kind_name": "고랭지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 231,
       "item_name": "무",
       "kind_code": 3,
       "kind_name": "가을",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 231,
       "item_name": "무",
       "kind_code": 6,
       "kind_name": "월동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 232,
       "item_name": "당근",
       "kind_code": 0,
       "kind_name": "당근",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 500,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 232,
       "item_name": "당근",
       "kind_code": 1,
       "kind_name": "무세척",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 232,
       "item_name": "당근",
       "kind_code": 2,
       "kind_name": "세척",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 232,
       "item_name": "당근",
       "kind_code": 10,
       "kind_name": "세척(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 233,
       "item_name": "열무",
       "kind_code": 0,
       "kind_name": "열무",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 241,
       "item_name": "건고추",
       "kind_code": 0,
       "kind_name": "화건",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 600,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 241,
       "item_name": "건고추",
       "kind_code": 1,
       "kind_name": "햇산화건",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 600,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 241,
       "item_name": "건고추",
       "kind_code": 2,
       "kind_name": "양건",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 600,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 241,
       "item_name": "건고추",
       "kind_code": 3,
       "kind_name": "햇산양건",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 600,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 241,
       "item_name": "건고추",
       "kind_code": 10,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 242,
       "item_name": "풋고추",
       "kind_code": 0,
       "kind_name": "풋고추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 242,
       "item_name": "풋고추",
       "kind_code": 2,
       "kind_name": "꽈리고추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 242,
       "item_name": "풋고추",
       "kind_code": 3,
       "kind_name": "청양고추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 242,
       "item_name": "풋고추",
       "kind_code": 4,
       "kind_name": "오이맛고추",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 243,
       "item_name": "붉은고추",
       "kind_code": 0,
       "kind_name": "붉은고추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 1,
       "kind_name": "한지1접",
       "wholesale_shipping_unit": "접",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 2,
       "kind_name": "난지1접",
       "wholesale_shipping_unit": "접",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 3,
       "kind_name": "한지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 4,
       "kind_name": "난지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 6,
       "kind_name": "햇한지1접",
       "wholesale_shipping_unit": "접",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 7,
       "kind_name": "햇난지1접",
       "wholesale_shipping_unit": "접",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 21,
       "kind_name": "햇난지(대서)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 22,
       "kind_name": "난지(대서)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 23,
       "kind_name": "햇난지(남도)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 244,
       "item_name": "피마늘",
       "kind_code": 24,
       "kind_name": "난지(남도)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 245,
       "item_name": "양파",
       "kind_code": 0,
       "kind_name": "양파",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 245,
       "item_name": "양파",
       "kind_code": 2,
       "kind_name": "햇양파",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 245,
       "item_name": "양파",
       "kind_code": 10,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 246,
       "item_name": "파",
       "kind_code": 0,
       "kind_name": "대파",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 300,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 246,
       "item_name": "파",
       "kind_code": 2,
       "kind_name": "쪽파",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 247,
       "item_name": "생강",
       "kind_code": 0,
       "kind_name": "국산",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 247,
       "item_name": "생강",
       "kind_code": 1,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 248,
       "item_name": "고춧가루",
       "kind_code": 0,
       "kind_name": "국산",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 248,
       "item_name": "고춧가루",
       "kind_code": 1,
       "kind_name": "중국",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 251,
       "item_name": "가지",
       "kind_code": 0,
       "kind_name": "가지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 200,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 252,
       "item_name": "미나리",
       "kind_code": 0,
       "kind_name": "미나리",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 15,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 253,
       "item_name": "깻잎",
       "kind_code": 0,
       "kind_name": "깻잎",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 30,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 254,
       "item_name": "부추",
       "kind_code": 0,
       "kind_name": "부추",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 200,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 255,
       "item_name": "피망",
       "kind_code": 0,
       "kind_name": "청",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 256,
       "item_name": "파프리카",
       "kind_code": 0,
       "kind_name": "파프리카",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 200,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 257,
       "item_name": "멜론",
       "kind_code": 0,
       "kind_name": "멜론",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 258,
       "item_name": "깐마늘(국산)",
       "kind_code": 1,
       "kind_name": "깐마늘(국산)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 600,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 258,
       "item_name": "깐마늘(국산)",
       "kind_code": 3,
       "kind_name": "깐마늘(대서)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 258,
       "item_name": "깐마늘(국산)",
       "kind_code": 4,
       "kind_name": "햇깐마늘(대서)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 258,
       "item_name": "깐마늘(국산)",
       "kind_code": 5,
       "kind_name": "깐마늘(남도)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 258,
       "item_name": "깐마늘(국산)",
       "kind_code": 6,
       "kind_name": "햇깐마늘(남도)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 259,
       "item_name": "깐마늘(수입)",
       "kind_code": 1,
       "kind_name": "깐마늘(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 259,
       "item_name": "깐마늘(수입)",
       "kind_code": 3,
       "kind_name": "깐마늘(수입산)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 261,
       "item_name": "브로콜리",
       "kind_code": 1,
       "kind_name": "브로콜리",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 262,
       "item_name": "양상추",
       "kind_code": 1,
       "kind_name": "양상추",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 263,
       "item_name": "청경채",
       "kind_code": 1,
       "kind_name": "청경채",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 264,
       "item_name": "케일",
       "kind_code": 1,
       "kind_name": "케일",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 265,
       "item_name": "콩나물",
       "kind_code": 1,
       "kind_name": "콩나물",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 300,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "채소류",
       "item_code": 422,
       "item_name": "방울토마토",
       "kind_code": 1,
       "kind_name": "방울토마토",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "채소류",
       "item_code": 422,
       "item_name": "방울토마토",
       "kind_code": 2,
       "kind_name": "대추방울토마토",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    }
 ]
const SPECIAL_CROPS = [
    {
       "item_category_name": "특용작물",
       "item_code": 312,
       "item_name": "참깨",
       "kind_code": 1,
       "kind_name": "백색(국산)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 312,
       "item_name": "참깨",
       "kind_code": 2,
       "kind_name": "중국",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 312,
       "item_name": "참깨",
       "kind_code": 3,
       "kind_name": "인도",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 500,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 313,
       "item_name": "들깨",
       "kind_code": 1,
       "kind_name": "국산",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 45,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 313,
       "item_name": "들깨",
       "kind_code": 2,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 45,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 314,
       "item_name": "땅콩",
       "kind_code": 1,
       "kind_name": "국산",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 314,
       "item_name": "땅콩",
       "kind_code": 2,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 30,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 315,
       "item_name": "느타리버섯",
       "kind_code": 0,
       "kind_name": "느타리버섯",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 315,
       "item_name": "느타리버섯",
       "kind_code": 1,
       "kind_name": "애느타리버섯",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 316,
       "item_name": "팽이버섯",
       "kind_code": 0,
       "kind_name": "팽이버섯",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 150,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 150,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "특용작물",
       "item_code": 317,
       "item_name": "새송이버섯",
       "kind_code": 0,
       "kind_name": "새송이버섯",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 300,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "특용작물",
       "item_code": 318,
       "item_name": "호두",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 319,
       "item_name": "아몬드",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "특용작물",
       "item_code": 321,
       "item_name": "양송이버섯",
       "kind_code": 1,
       "kind_name": "양송이버섯",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 130,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "특용작물",
       "item_code": 322,
       "item_name": "표고버섯",
       "kind_code": 1,
       "kind_name": "표고버섯",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 100,
       "wholesale_grade": null,
       "retail_grade": null,
       "organic_grade": "07,08"
    }
 ]
const FRUITS = [
    {
       "item_category_name": "과일류",
       "item_code": 411,
       "item_name": "사과",
       "kind_code": 1,
       "kind_name": "홍옥",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 411,
       "item_name": "사과",
       "kind_code": 5,
       "kind_name": "후지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 1.5,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "과일류",
       "item_code": 411,
       "item_name": "사과",
       "kind_code": 6,
       "kind_name": "쓰가루",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 411,
       "item_name": "사과",
       "kind_code": 7,
       "kind_name": "홍로",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 412,
       "item_name": "배",
       "kind_code": 1,
       "kind_name": "신고",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 15,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 300,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "과일류",
       "item_code": 412,
       "item_name": "배",
       "kind_code": 2,
       "kind_name": "만삼길",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 15,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 412,
       "item_name": "배",
       "kind_code": 3,
       "kind_name": "장십랑",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 15,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 412,
       "item_name": "배",
       "kind_code": 4,
       "kind_name": "원황",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 15,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 413,
       "item_name": "복숭아",
       "kind_code": 1,
       "kind_name": "백도",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4.5,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 413,
       "item_name": "복숭아",
       "kind_code": 4,
       "kind_name": "창방조생",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4.5,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 413,
       "item_name": "복숭아",
       "kind_code": 5,
       "kind_name": "유명",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 4.5,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 1,
       "kind_name": "캠벨얼리",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 2,
       "kind_name": "거봉",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 2,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 3,
       "kind_name": "델라웨어",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 6,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 6,
       "kind_name": "MBA",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 7,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 8,
       "kind_name": "레드글로브 칠레",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 9,
       "kind_name": "레드글로브 페루",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 10,
       "kind_name": "톰슨 미국",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 11,
       "kind_name": "톰슨 호주",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 8,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 414,
       "item_name": "포도",
       "kind_code": 12,
       "kind_name": "샤인머스켓",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 2,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 415,
       "item_name": "감귤",
       "kind_code": 0,
       "kind_name": "감귤",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": "kg",
       "organic_shipping_scale": 3,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "과일류",
       "item_code": 415,
       "item_name": "감귤",
       "kind_code": 1,
       "kind_name": "노지",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "15,16",
       "retail_grade": "13,14",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 415,
       "item_name": "감귤",
       "kind_code": 2,
       "kind_name": "시설",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 3,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "15,16",
       "retail_grade": "13,14",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 416,
       "item_name": "단감",
       "kind_code": 0,
       "kind_name": "단감",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": "g",
       "organic_shipping_scale": 500,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": "07,08"
    },
    {
       "item_category_name": "과일류",
       "item_code": 418,
       "item_name": "바나나",
       "kind_code": 2,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 13,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 419,
       "item_name": "참다래",
       "kind_code": 1,
       "kind_name": "국산",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 419,
       "item_name": "참다래",
       "kind_code": 2,
       "kind_name": "그린 뉴질랜드",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 420,
       "item_name": "파인애플",
       "kind_code": 2,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 12,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 421,
       "item_name": "오렌지",
       "kind_code": 2,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 18,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 421,
       "item_name": "오렌지",
       "kind_code": 3,
       "kind_name": "네이블 미국",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 18,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 421,
       "item_name": "오렌지",
       "kind_code": 4,
       "kind_name": "발렌시아 미국",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 18,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 421,
       "item_name": "오렌지",
       "kind_code": 5,
       "kind_name": "네이블 EU",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 18,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 421,
       "item_name": "오렌지",
       "kind_code": 6,
       "kind_name": "네이블 호주",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 18,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 423,
       "item_name": "자몽",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 424,
       "item_name": "레몬",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 17,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 425,
       "item_name": "체리",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 426,
       "item_name": "건포도",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 427,
       "item_name": "건블루베리",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "과일류",
       "item_code": 428,
       "item_name": "망고",
       "kind_code": 0,
       "kind_name": "수입",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 5,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04,05",
       "retail_grade": "04,05",
       "organic_grade": null
    }
 ]
const LIVESTOCK_PRODUCTS = [
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 11,
       "kind_name": "한우갈비",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,03,17",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 12,
       "kind_name": "한우등심",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,03,17",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 13,
       "kind_name": "한우불고기",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,03",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 14,
       "kind_name": "한우양지",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,17",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 15,
       "kind_name": "한우안심",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,17",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 16,
       "kind_name": "한우설도",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "01,03,17",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 21,
       "kind_name": "미국산갈비",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 22,
       "kind_name": "미국산갈비살",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 23,
       "kind_name": "미국산불고기",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 24,
       "kind_name": "미국산설도",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 31,
       "kind_name": "호주산갈비",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 32,
       "kind_name": "호주산등심",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 33,
       "kind_name": "호주산불고기",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 512,
       "item_name": "쇠고기",
       "kind_code": 34,
       "kind_name": "호주산설도",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "10,11",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 514,
       "item_name": "돼지고기",
       "kind_code": 0,
       "kind_name": "삼겹살(국산냉장)",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 514,
       "item_name": "돼지고기",
       "kind_code": 1,
       "kind_name": "삼겹살(수입냉동)",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 514,
       "item_name": "돼지고기",
       "kind_code": 2,
       "kind_name": "목살",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 514,
       "item_name": "돼지고기",
       "kind_code": 3,
       "kind_name": "돼지갈비",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 514,
       "item_name": "돼지고기",
       "kind_code": 4,
       "kind_name": "앞다리살",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 515,
       "item_name": "닭고기",
       "kind_code": 2,
       "kind_name": "도계",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 516,
       "item_name": "계란",
       "kind_code": 0,
       "kind_name": "특란",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 30,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 516,
       "item_name": "계란",
       "kind_code": 1,
       "kind_name": "특란(소비쿠폰 적용)",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "개",
       "retail_shipping_scale": 30,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "축산물",
       "item_code": 535,
       "item_name": "우유",
       "kind_code": 0,
       "kind_name": "우유",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "리터",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    }
 ]
const MARINE_PRODUCTS =  [
    {
       "item_category_name": "수산물",
       "item_code": 611,
       "item_name": "고등어",
       "kind_code": 1,
       "kind_name": "생선",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 611,
       "item_name": "고등어",
       "kind_code": 2,
       "kind_name": "냉동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 611,
       "item_name": "고등어",
       "kind_code": 3,
       "kind_name": "염장",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 2,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 611,
       "item_name": "고등어",
       "kind_code": 4,
       "kind_name": "냉동(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 612,
       "item_name": "꽁치",
       "kind_code": 1,
       "kind_name": "냉동(수입)",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 5,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 613,
       "item_name": "갈치",
       "kind_code": 1,
       "kind_name": "생선",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 613,
       "item_name": "갈치",
       "kind_code": 2,
       "kind_name": "냉동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 615,
       "item_name": "명태",
       "kind_code": 1,
       "kind_name": "생선",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 615,
       "item_name": "명태",
       "kind_code": 2,
       "kind_name": "냉동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 619,
       "item_name": "물오징어",
       "kind_code": 1,
       "kind_name": "생선",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 619,
       "item_name": "물오징어",
       "kind_code": 2,
       "kind_name": "냉동",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 638,
       "item_name": "건멸치",
       "kind_code": 0,
       "kind_name": "건멸치",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1.5,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 639,
       "item_name": "북어",
       "kind_code": 1,
       "kind_name": "황태",
       "wholesale_shipping_unit": "마리",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 639,
       "item_name": "북어",
       "kind_code": 2,
       "kind_name": "먹태",
       "wholesale_shipping_unit": "마리",
       "wholesale_shipping_scale": 10,
       "retail_shipping_unit": null,
       "retail_shipping_scale": null,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": null,
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 640,
       "item_name": "건오징어",
       "kind_code": 0,
       "kind_name": "건오징어",
       "wholesale_shipping_unit": "마리",
       "wholesale_shipping_scale": 20,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 641,
       "item_name": "김",
       "kind_code": 0,
       "kind_name": "마른김",
       "wholesale_shipping_unit": "속",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "장",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 641,
       "item_name": "김",
       "kind_code": 1,
       "kind_name": "얼구운김",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "장",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 642,
       "item_name": "건미역",
       "kind_code": 0,
       "kind_name": "건미역",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "g",
       "retail_shipping_scale": 100,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 644,
       "item_name": "굴",
       "kind_code": 0,
       "kind_name": "굴",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "04",
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 649,
       "item_name": "수입조기",
       "kind_code": 1,
       "kind_name": "부세수입(생선)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 649,
       "item_name": "수입조기",
       "kind_code": 4,
       "kind_name": "부세수입(냉동)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 650,
       "item_name": "새우젓",
       "kind_code": 0,
       "kind_name": "새우젓",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 651,
       "item_name": "멸치액젓",
       "kind_code": 0,
       "kind_name": "멸치액젓",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 1,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 652,
       "item_name": "굵은소금",
       "kind_code": 0,
       "kind_name": "굵은소금",
       "wholesale_shipping_unit": null,
       "wholesale_shipping_scale": null,
       "retail_shipping_unit": "kg",
       "retail_shipping_scale": 5,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": null,
       "retail_grade": "04",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 653,
       "item_name": "전복",
       "kind_code": 0,
       "kind_name": "전복",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 1,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 5,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    },
    {
       "item_category_name": "수산물",
       "item_code": 654,
       "item_name": "새우",
       "kind_code": 1,
       "kind_name": "흰다리(수입)",
       "wholesale_shipping_unit": "kg",
       "wholesale_shipping_scale": 2,
       "retail_shipping_unit": "마리",
       "retail_shipping_scale": 10,
       "organic_shipping_unit": null,
       "organic_shipping_scale": null,
       "wholesale_grade": "05",
       "retail_grade": "05",
       "organic_grade": null
    }
 ]
 const PRODUCT_LIST:IProductList[] = [
    {
       category_Code : "100",
       name : "식량작물",
       list : FOOD_CROPS,
    },
    {
      category_Code : "200",
      name : "채소류",
      list : VEGETABLES,
   },
   {
      category_Code : "300",
      name : "특용작물",
      list : SPECIAL_CROPS,
   },
   {
      category_Code : "400",
      name : "과일류",
      list : FRUITS,
   },
   {
      category_Code : "500",
      name : "축산물",
      list : LIVESTOCK_PRODUCTS,
   },
   {
      category_Code : "600",
      name : "수산물",
      list : MARINE_PRODUCTS,
   },
 ]
 
 
 
export default PRODUCT_LIST;